name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ "**" ]
  workflow_dispatch: {}

env:
  GO_VERSION: "1.24.x"
  IMAGE_REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}  # e.g. owner/repo

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: true

      - name: Go mod tidy
        run: go mod tidy

      - name: Vet
        run: go vet ./...

      - name: Test
        run: go test -race -count=1 ./...

      - name: Build binary
        run: CGO_ENABLED=0 go build -trimpath -ldflags="-s -w" -o bin/weather-service ./cmd/server

      - name: Upload artifact (binary)
        uses: actions/upload-artifact@v4
        with:
          name: weather-service
          path: bin/weather-service

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # required to push to GHCR with GITHUB_TOKEN
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extract metadata (tags, labels)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=sha,format=short
            type=ref,event=branch
            type=raw,value=latest,enable=${{ github.ref == 'refs/heads/main' }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          file: Dockerfile
          build-args: |
            GO_VERSION=1.24
          platforms: linux/amd64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Summary
        run: |
          echo "Pushed image(s):"
          echo "${{ steps.meta.outputs.tags }}"
